services:
   web:
    build: .
    command:  >
      sh -c "python manage.py migrate --settings=vercel_app.docker && 
             python manage.py runserver 0.0.0.0:8000 --settings=vercel_app.docker"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mongo
    networks:
      - my_network

   db:
    image: postgres:13.15-bullseye
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - my_network
   
   mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    networks:
      - my_network

networks:
  my_network:
    driver: bridge